**Lambda Functions**

syntax

name of function =lambda x:

(everything must be in same line)


In [12]:
#multiplication
func = lambda x: x*x

In [14]:
#call the function to get output
fun(5)

25

In [16]:
#two take two inputs for multiplication
func1 = lambda x,y: x*y

In [20]:
func1(3,6)

18

In [24]:
#to check if number is even or odd
func2 = lambda x: 'even' if x%2==0 else 'odd'

In [28]:
func2(5)

'odd'

In [30]:
#to check even and odd numbers in a list
list1 =[1,2,3,4,5,6,7,8]
func3=lambda x: ['even' if x%2==0 else 'odd' for x in list1]

In [34]:
func3(list1)

['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even']

**filter**

In [47]:
#to find numbers greater than 10 in a list using functions
list2 =[1,45,7,3,56,3,67]
def large (x):
    if x>10:
        return x
list(filter(large,list2))

[45, 56, 67]

In [53]:
##to find numbers greater than 10 in a list using lambda functions
list(filter(lambda x:x>10,list2))

[45, 56, 67]

**Numpy- Numerical Python**

NumPy is usually imported under the np alias.

NumPy is a Python library used for working with arrays. Used to perform multiple mathematical functions.

**Array**- An array is a special variable, which can hold more than one value at a time.

In [58]:
#for importing numpy library
import numpy as np

An array is a special variable, which can hold more than one value at a time

**One-dimensional array**

In [63]:
#1D array
one_dim = np.array([1, 2, 3, 4, 5])
one_dim

array([1, 2, 3, 4, 5])

In [65]:
#size
one_dim.size

5

In [67]:
#to check dimension
one_dim.ndim

1

In [69]:
#to access an element
one_dim[3]

4

In [85]:
#to add an element
one_dim[3]=52
one_dim

array([ 1,  2,  3, 52,  5])

In [87]:
#to delete an element
new=np.delete(one_dim,3)
new

array([1, 2, 3, 5])

In [81]:
#to find maximum value
np.max(one_dim)

52

In [91]:
#to find minimum value
np.min(one_dim)

1

In [93]:
#to find mean
np.mean(one_dim)

12.6

In [95]:
#to find median
np.median(one_dim)

3.0

In [97]:
#to get only unique values by ignoring duplicates
np.unique(one_dim)

array([ 1,  2,  3,  5, 52])

In [99]:
#to get index of the greatest number in array
np.argmax(one_dim)

3

In [101]:
#to get index of the greatest number in array
np.min(one_dim)

1

**two-dimensional array**

In [106]:
#2D array
two_dim=np.array([[1,2,3],[4,5,6],[7,8,9]])
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
#to check dimension
two_dim.ndim

2

In [110]:
#to know the numbers of rows and columns
two_dim.shape

(3, 3)

In [112]:
#to know the number of elements
two_dim.size

9

In [116]:
#to access 6th element
two_dim[1,2]

6

In [120]:
#to access first row
two_dim[0]

array([1, 2, 3])

In [122]:
#to access first and second row
two_dim[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
#to access first column
two_dim[ : ,0]

array([1, 4, 7])

In [126]:
#to access first two columns
two_dim[ : ,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [130]:
#to change 3rd row
two_dim[2]=[30,40,50]
two_dim

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [30, 40, 50]])

In [136]:
#to change 2nd column
two_dim[:,1]=[22,33,44]
two_dim

array([[ 1, 22,  3],
       [ 4, 33,  6],
       [30, 44, 50]])