**2D numpy array continuation**

In [38]:
import numpy as np

In [7]:
#2D array
two_dim=np.array([[1,2,3],[4,5,6],[7,8,9]])
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**to delete a row**

In [16]:
#use delete function(array name,row which we want to delete, axis=0 for any row)
np.delete(two_dim,2,axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

**to delete a column**

In [18]:
#use delete function(array name,column which we want to delete, axis=1 for any column)
np.delete(two_dim,1,axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

**arrange function- to give list of numbers in order specified in range**

In [26]:
np.arange(1, 12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**reshape- is used to change the shape of an array without changing its data**

In [42]:
#4x4 matrix of numbers in order from 1-16
two_dim1 = np.arange(1, 17).reshape(4, 4)
two_dim1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

**random- to get a random value within a range**

In [44]:
np.random.randint(10,100)

26

In [47]:
#10 random numbers- np.random.randint(range,number of values)
np.random.randint(10,100,10)

array([87, 69, 95, 20, 88, 36, 53, 39, 45, 20])

In [53]:
##10 random numbers in a 2D array- np.random.randint(range,number of values).reshape(rowsxcolumns)
np.random.randint(10,100,9).reshape(3,3)

array([[33, 40, 82],
       [49, 43, 97],
       [88, 54, 35]])

In [55]:
#max value
np.max(two_dim)

9

In [57]:
#min value
np.min(two_dim)

1

In [61]:
#mean
np.mean(two_dim)

5.0

In [63]:
#median
np.median(two_dim)

5.0

In [65]:
#transpose- columns become rows
np.transpose(two_dim)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [67]:
#maximum value index
np.argmax(two_dim)

8

In [69]:
#minimum value index
np.argmin(two_dim)

0

In [75]:
#determinant using line algorithmn function
np.linalg.det(two_dim)

-9.51619735392994e-16

In [77]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,7,2],[8,1,3],[10,45,3]])

In [79]:
#addition
a+b

array([[ 5,  9,  5],
       [12,  6,  9],
       [17, 53, 12]])

In [81]:
#subtraction
a-b

array([[ -3,  -5,   1],
       [ -4,   4,   3],
       [ -3, -37,   6]])

In [83]:
#matrix multiplication
a@b

array([[ 50, 144,  17],
       [116, 303,  41],
       [182, 462,  65]])

In [85]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])